"""
Load step: take extract.py's books and transform.py's themes (see themes.json
-- currently generated by hand for the first 50 books rather than a live LLM
API call; see README) and write nodes/books/edges into Postgres.

Strategy: full refresh. Every run truncates and rebuilds the graph from the
current extracted_books.json + themes.json rather than diffing/upserting.
At this scale (dozens to low hundreds of books) that's simpler than upsert
logic and just as correct -- the source of truth is always the two JSON
files, never the database. Worth revisiting if this ever needs to run
incrementally against thousands of books.

Similarity weights are a plain, inspectable formula -- not a model score:

    weight = jaccard(themesA, themesB) + (0.1 if same genre else 0)

jaccard = |shared themes| / |themes A union themes B|. That keeps every
SIMILAR_TO edge's weight traceable back to the actual themes two books share,
which is the whole point per docs/architecture.md.
"""

import json
import os
from itertools import combinations
from pathlib import Path

import psycopg
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent / ".env")

DATA_DIR = Path(__file__).parent / "data"


def load_source_data():
    books = json.load(open(DATA_DIR / "extracted_books.json"))
    themes = json.load(open(DATA_DIR / "themes.json"))
    # Only load books we actually have theme data for (first 50 -- see README).
    books = [b for b in books if b["title"] in themes]
    return books, themes


def get_or_create_node(cur, node_type: str, name: str, external_id: str | None = None) -> int:
    if external_id is not None:
        cur.execute(
            "INSERT INTO nodes (type, name, external_id) VALUES (%s, %s, %s) "
            "ON CONFLICT (external_id) WHERE external_id IS NOT NULL DO UPDATE SET name = EXCLUDED.name "
            "RETURNING id",
            (node_type, name, external_id),
        )
        return cur.fetchone()[0]

    cur.execute("SELECT id FROM nodes WHERE type = %s AND name = %s", (node_type, name))
    row = cur.fetchone()
    if row:
        return row[0]
    cur.execute(
        "INSERT INTO nodes (type, name) VALUES (%s, %s) RETURNING id",
        (node_type, name),
    )
    return cur.fetchone()[0]


def insert_edge(cur, source_id: int, target_id: int, rel_type: str, weight: float, explanation: str):
    cur.execute(
        "INSERT INTO edges (source_node_id, target_node_id, relationship_type, weight, explanation) "
        "VALUES (%s, %s, %s, %s, %s)",
        (source_id, target_id, rel_type, weight, explanation),
    )


def load(conn):
    books, themes = load_source_data()

    with conn.cursor() as cur:
        cur.execute("TRUNCATE edges, books, nodes RESTART IDENTITY CASCADE")

        book_node_id: dict[str, int] = {}
        book_topics: dict[str, set[str]] = {}

        for b in books:
            info = themes[b["title"]]

            book_id = get_or_create_node(cur, "BOOK", b["title"], external_id=b["external_id"])
            book_node_id[b["title"]] = book_id
            cur.execute(
                "INSERT INTO books (node_id, summary, author_text, published_year, cover_url) "
                "VALUES (%s, %s, %s, %s, %s) "
                "ON CONFLICT (node_id) DO UPDATE SET summary = EXCLUDED.summary, author_text = EXCLUDED.author_text",
                (book_id, b["video_script"], b["author"], None, None),
            )

            if b["author"]:
                author_id = get_or_create_node(cur, "AUTHOR", b["author"])
                insert_edge(cur, book_id, author_id, "WRITTEN_BY", 1.0, f"Written by {b['author']}.")

            genre_id = get_or_create_node(cur, "GENRE", info["genre"])
            insert_edge(cur, book_id, genre_id, "BELONGS_TO_GENRE", 1.0, f"Categorized as {info['genre']}.")

            topic_names = set()
            for topic in info["topics"]:
                topic_id = get_or_create_node(cur, "TOPIC", topic["name"])
                insert_edge(cur, book_id, topic_id, "DISCUSSES", 1.0, topic["explanation"])
                topic_names.add(topic["name"])
            book_topics[b["title"]] = topic_names

        # SIMILAR_TO: one edge per unordered book pair with at least one shared
        # theme. weight = jaccard(themes) + 0.1 if same genre (capped at 1.0).
        genre_of = {b["title"]: themes[b["title"]]["genre"] for b in books}
        similar_edges = 0
        for title_a, title_b in combinations(book_topics.keys(), 2):
            shared = book_topics[title_a] & book_topics[title_b]
            if not shared:
                continue
            union = book_topics[title_a] | book_topics[title_b]
            weight = len(shared) / len(union)
            if genre_of[title_a] == genre_of[title_b]:
                weight = min(1.0, weight + 0.1)
            explanation = f"Shares {len(shared)} theme(s): {', '.join(sorted(shared))}."
            insert_edge(
                cur,
                book_node_id[title_a],
                book_node_id[title_b],
                "SIMILAR_TO",
                round(weight, 3),
                explanation,
            )
            similar_edges += 1

    conn.commit()
    return len(books), similar_edges


def main():
    database_url = os.environ["DATABASE_URL"]
    with psycopg.connect(database_url) as conn:
        book_count, similar_edges = load(conn)
        with conn.cursor() as cur:
            cur.execute("SELECT count(*) FROM nodes")
            node_count = cur.fetchone()[0]
            cur.execute("SELECT count(*) FROM edges")
            edge_count = cur.fetchone()[0]
    print(f"Loaded {book_count} books -> {node_count} nodes, {edge_count} edges ({similar_edges} of them SIMILAR_TO)")


if __name__ == "__main__":
    main()
